# Generated by Django 4.2.4 on 2023-08-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priority',
            new_name='Task',
        ),
    ]
